from fastapi import APIRouter, Request, HTTPException
from pydantic import BaseModel, Field
from typing import Optional
from backend.config import settings
from backend.services.github_service import GitHubService
from backend.services.repo_processor import RepoProcessor
from backend.services.llm_service import LLMService, SummaryResponse


class SummarizeRequest(BaseModel):
    """Request body for the summarize endpoint."""
    github_url: str = Field(..., description="URL of a GitHub repository")


class ErrorResponse(BaseModel):
    """Error response format."""
    status: str = "error"
    message: str


router = APIRouter(prefix="/api", tags=["summarize"])


@router.post("/summarize", response_model=SummaryResponse)
async def summarize(request: SummarizeRequest, req: Request) -> SummaryResponse:
    """
    Analyze a GitHub repository and return a summary.

    Takes a GitHub repository URL, fetches the repository contents, and returns
    a summary generated by an LLM.
    """
    # Check for provider/API key overrides in request headers
    provider_override = req.headers.get("X-Provider")
    api_key_override = req.headers.get("X-Api-Key")

    try:
        # Validate URL
        if not request.github_url or "github.com" not in request.github_url.lower():
            raise HTTPException(
                status_code=400,
                detail="Invalid GitHub URL. Expected: https://github.com/owner/repo"
            )

        # Get GitHub token from request headers (if provided by frontend) or use env var
        github_token = req.headers.get("X-Github-Token") or settings.github_token

        # Fetch repository tree
        github_service = GitHubService(github_token=github_token)
        try:
            # Process repository
            processor = RepoProcessor()
            processed = await processor.process(request.github_url, github_service)

            # Generate summary
            llm_service = LLMService(
                settings=settings,
                provider_override=provider_override,
                api_key_override=api_key_override,
            )
            result = await llm_service.summarize_repo(processed)
            return result

        except HTTPException:
            # Re-raise HTTP exceptions as-is
            raise
        except Exception as inner_error:
            # Catch any other exception and provide more info
            raise HTTPException(
                status_code=500,
                detail=f"Error: {type(inner_error).__name__}: {str(inner_error)}"
            )
        finally:
            await github_service.close()

    except HTTPException:
        raise
    except ValueError as e:
        # LLM service initialization error (missing API key)
        raise HTTPException(status_code=503, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Internal server error: {str(e)}")
