import logging
from fastapi import APIRouter, Request, HTTPException
from pydantic import BaseModel, Field
from typing import Optional
from backend.config import settings
from backend.services.github_service import GitHubService
from backend.services.repo_processor import RepoProcessor
from backend.services.llm_service import LLMService, SummaryResponse
from backend.debug import DebugLogger, debug_timer

# Set up logging
logger = logging.getLogger(__name__)
debug_logger = DebugLogger(__name__)
logging.basicConfig(level=logging.DEBUG)


class SummarizeRequest(BaseModel):
    """Request body for the summarize endpoint."""
    github_url: str = Field(..., description="URL of a GitHub repository")


class ErrorResponse(BaseModel):
    """Error response format."""
    status: str = "error"
    message: str


router = APIRouter(prefix="/api", tags=["summarize"])


@router.post("/summarize", response_model=SummaryResponse)
async def summarize(request: SummarizeRequest, req: Request) -> SummaryResponse:
    """
    Analyze a GitHub repository and return a summary.

    Takes a GitHub repository URL, fetches the repository contents, and returns
    a summary generated by an LLM.
    """
    debug_logger.log_request("POST", "/api/summarize", url=request.github_url)
    debug_logger.start_timer("summarize_endpoint")

    logger.info(f"🔵 /api/summarize endpoint hit!")
    logger.info(f"📋 Request body: {request}")
    logger.info(f"📍 Request path: {req.url.path}")
    logger.info(f"🔗 Request URL: {req.url}")

    # Check for provider/API key overrides in request headers
    provider_override = req.headers.get("X-Provider")
    api_key_override = req.headers.get("X-Api-Key")

    debug_logger.log_debug(f"Provider override: {provider_override}")
    debug_logger.log_debug(f"API key override: {'***' if api_key_override else 'None'}")

    logger.info(f"🔐 Provider override: {provider_override}")
    logger.info(f"🔑 API key override: {'***' if api_key_override else 'None'}")

    try:
        # Validate URL
        if not request.github_url or "github.com" not in request.github_url.lower():
            debug_logger.log_error("Invalid GitHub URL format")
            raise HTTPException(
                status_code=400,
                detail="Invalid GitHub URL. Expected: https://github.com/owner/repo"
            )

        # Get GitHub token from request headers (if provided by frontend) or use env var
        github_token = req.headers.get("X-Github-Token") or settings.github_token
        debug_logger.log_debug(f"Using GitHub token: {'***' if github_token else 'None'}")

        # Fetch repository tree
        github_service = GitHubService(github_token=github_token)
        try:
            # Process repository
            debug_logger.log_debug("Starting repository processing...")
            processor = RepoProcessor()
            processed = await processor.process(request.github_url, github_service)
            debug_logger.log_success(f"Repository processed: {processed.owner}/{processed.repo}")
            debug_logger.log_data("Processed repo stats", {
                "owner": processed.owner,
                "repo": processed.repo,
                "total_files": processed.total_files_count,
                "fetched_files": processed.fetched_files_count,
            })

            # Generate summary
            debug_logger.log_debug("Starting LLM summary generation...")
            llm_service = LLMService(
                settings=settings,
                provider_override=provider_override,
                api_key_override=api_key_override,
            )
            result = await llm_service.summarize_repo(processed)

            duration_ms = debug_logger.end_timer("summarize_endpoint")
            debug_logger.log_response(200, duration_ms)
            debug_logger.log_success(f"Repository summarized in {duration_ms:.1f}ms")
            return result

        except HTTPException:
            # Re-raise HTTP exceptions as-is
            raise
        except Exception as inner_error:
            # Catch any other exception and provide more info
            debug_logger.log_error("Error processing repository", error=inner_error)
            raise HTTPException(
                status_code=500,
                detail=f"Error: {type(inner_error).__name__}: {str(inner_error)}"
            )
        finally:
            await github_service.close()

    except HTTPException as http_error:
        duration_ms = debug_logger.end_timer("summarize_endpoint")
        debug_logger.log_response(http_error.status_code, duration_ms)
        raise
    except ValueError as e:
        # LLM service initialization error (missing API key)
        debug_logger.log_error("Missing API key", error=e)
        debug_logger.log_response(503, debug_logger.end_timer("summarize_endpoint"))
        raise HTTPException(status_code=503, detail=str(e))
    except Exception as e:
        debug_logger.log_error("Internal server error", error=e)
        debug_logger.log_response(500, debug_logger.end_timer("summarize_endpoint"))
        raise HTTPException(status_code=500, detail=f"Internal server error: {str(e)}")
